name: jared-teaching-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - nodejs
  - texlive-xetex 
  - texlive-fonts-recommended 
  - texlive-generic-recommended
  - pip:
    - jupyterlab
    - nbgitpuller
    - jupyterlab_github
    - sphinx-gallery
    - pandas
    - matplotlib
    - nbgrader
    - seaborn
    - numpy
    - scikit-learn
    - scikit-plot
    - graphviz 
    - pandas_profiling
    - gensim
    - nltk
