name: jared-teaching-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - jupyterlab
    - nbgitpuller
    - jupyterlab_github
    - sphinx-gallery
    - pandas
    - matplotlib
    - nbgrader
    - seaborn
    - numpy
    - scikit-learn
    - graphviz 
    - pandas_profiling
