name: jared-teaching-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - nodejs
  - pip:
    - jupyterlab
    - nbgitpuller
#    - jupyterlab_github
#    - sphinx-gallery
    - pandas
    - matplotlib
#    - nbgrader
#    - seaborn
    - numpy
    - scikit-learn
    - scikit-plot
    - graphviz 
    - pandas_profiling
    - gensim
    - nltk
#    - jupyterlab_latex
    - feather-format
    - statsmodels
