name: jared-teaching-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - jupyterlab
    - nbgrader
    - seaborn
    - numpy
