#!/bin/bash

set -ex

jupyter lab clean
jupyter labextension install @jupyterlab/toc
jupyter labextension install @aquirdturtle/collapsible_headings
jupyter labextension install @jupyterlab/github
jupyter labextension install @jupyterlab/debugger

jupyter labextension update --all
jupyter lab build

